"""Get a word-level transcript, in order of preference.

  1. YouTube's own subtitle track (instant, free, already published by the
     uploader or auto-generated by YouTube). `json3` is preferred because it
     carries per-word offsets.
  2. Local Whisper via faster-whisper - accurate word timings for any video,
     but costs CPU. Optional dependency; the app degrades gracefully.
  3. Nothing - the pipeline falls back to audio-only segmentation.
"""
from __future__ import annotations

import json
import re
from collections.abc import Callable
from pathlib import Path

from ..analyzers.segmentation import segment_words
from ..analyzers.types import Transcript, Word
from ..config import settings
from ..utils.logging import get_logger

log = get_logger(__name__)

_VTT_CUE = re.compile(
    r"(?P<start>\d{2}:\d{2}:\d{2}[.,]\d{3})\s*-->\s*(?P<end>\d{2}:\d{2}:\d{2}[.,]\d{3})"
)
_VTT_INLINE = re.compile(r"<(\d{2}:\d{2}:\d{2}[.,]\d{3})>")
_TAG = re.compile(r"</?[cvbi][^>]*>|</?\d[^>]*>")
_SRT_INDEX = re.compile(r"^\d+$")


def _parse_clock(value: str) -> float:
    value = value.replace(",", ".")
    hours, minutes, seconds = value.split(":")
    return int(hours) * 3600 + int(minutes) * 60 + float(seconds)


# --------------------------------------------------------------------------
# YouTube json3 (best: real per-word offsets)
# --------------------------------------------------------------------------
def parse_json3(path: Path) -> list[Word]:
    try:
        data = json.loads(Path(path).read_text(encoding="utf-8", errors="replace"))
    except (OSError, json.JSONDecodeError) as exc:
        log.warning("could not read %s: %s", path.name, exc)
        return []

    words: list[Word] = []
    events = data.get("events") or []
    for event in events:
        segs = event.get("segs")
        if not segs:
            continue
        base_ms = event.get("tStartMs")
        if base_ms is None:
            continue
        duration_ms = event.get("dDurationMs") or 0
        event_end = (base_ms + duration_ms) / 1000.0

        pending: list[tuple[str, float]] = []
        for seg in segs:
            text = (seg.get("utf8") or "").strip()
            if not text or text == "\n":
                continue
            offset = seg.get("tOffsetMs")
            start = (base_ms + (offset or 0)) / 1000.0
            pending.append((text, start))

        for i, (text, start) in enumerate(pending):
            end = pending[i + 1][1] if i + 1 < len(pending) else max(event_end, start + 0.28)
            if end <= start:
                end = start + 0.28
            words.append(Word(text=text, start=round(start, 3), end=round(end, 3)))

    return _dedupe(words)


# --------------------------------------------------------------------------
# WebVTT / SRT
# --------------------------------------------------------------------------
def parse_vtt(path: Path) -> list[Word]:
    try:
        raw = Path(path).read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        log.warning("could not read %s: %s", path.name, exc)
        return []

    words: list[Word] = []
    lines = raw.splitlines()
    i = 0
    while i < len(lines):
        cue = _VTT_CUE.search(lines[i])
        if not cue:
            i += 1
            continue
        cue_start = _parse_clock(cue.group("start"))
        cue_end = _parse_clock(cue.group("end"))
        i += 1

        body: list[str] = []
        while i < len(lines) and lines[i].strip() and not _VTT_CUE.search(lines[i]):
            if not _SRT_INDEX.match(lines[i].strip()):
                body.append(lines[i])
            i += 1

        text_block = " ".join(body)
        if not text_block.strip():
            continue

        # YouTube auto-captions embed per-word timestamps like:
        #   hello<00:00:01.200><c> world</c>
        if _VTT_INLINE.search(text_block):
            words.extend(_parse_inline_timed(text_block, cue_start, cue_end))
        else:
            cleaned = _TAG.sub("", text_block)
            cleaned = " ".join(cleaned.split())
            tokens = cleaned.split()
            if not tokens:
                continue
            span = max(0.2, cue_end - cue_start)
            step = span / len(tokens)
            for idx, token in enumerate(tokens):
                start = cue_start + idx * step
                words.append(
                    Word(text=token, start=round(start, 3), end=round(start + step, 3))
                )

    return _dedupe(words)


def _parse_inline_timed(block: str, cue_start: float, cue_end: float) -> list[Word]:
    parts = _VTT_INLINE.split(block)
    words: list[Word] = []
    current_time = cue_start

    # split() alternates: [text, ts, text, ts, text, ...]
    for index, part in enumerate(parts):
        if index % 2 == 1:
            current_time = _parse_clock(part)
            continue
        cleaned = " ".join(_TAG.sub("", part).split())
        if not cleaned:
            continue
        tokens = cleaned.split()
        step = 0.28
        for offset, token in enumerate(tokens):
            start = current_time + offset * step
            words.append(Word(text=token, start=round(start, 3), end=round(start + step, 3)))
        current_time += len(tokens) * step

    for i in range(len(words) - 1):
        if words[i].end > words[i + 1].start:
            words[i] = Word(words[i].text, words[i].start, words[i + 1].start)
    if words and words[-1].end > cue_end:
        words[-1] = Word(words[-1].text, words[-1].start, max(cue_end, words[-1].start + 0.15))
    return words


def _dedupe(words: list[Word]) -> list[Word]:
    """Rolling captions repeat lines; drop the repeats."""
    words = sorted((w for w in words if w.text.strip()), key=lambda w: (w.start, w.end))
    out: list[Word] = []
    for word in words:
        if out:
            last = out[-1]
            same_text = last.text.strip().lower() == word.text.strip().lower()
            if same_text and abs(last.start - word.start) < 0.35:
                continue
            if word.start < last.start:
                continue
        out.append(word)
    return out


# --------------------------------------------------------------------------
# Whisper fallback
# --------------------------------------------------------------------------
def whisper_available() -> bool:
    try:
        import faster_whisper  # noqa: F401
    except Exception:
        return False
    return True


_WHISPER_MODEL = None


def _load_whisper():
    global _WHISPER_MODEL
    if _WHISPER_MODEL is None:
        from faster_whisper import WhisperModel

        log.info("loading Whisper model '%s' (first run downloads it)", settings.whisper_model)
        _WHISPER_MODEL = WhisperModel(
            settings.whisper_model, device="cpu", compute_type="int8"
        )
    return _WHISPER_MODEL


def transcribe_with_whisper(
    media_path: Path,
    *,
    duration: float,
    on_progress: Callable[[float], None] | None = None,
) -> list[Word]:
    model = _load_whisper()
    segments, _info = model.transcribe(
        str(media_path),
        word_timestamps=True,
        vad_filter=True,
        vad_parameters={"min_silence_duration_ms": 400},
        beam_size=1,
    )

    words: list[Word] = []
    for segment in segments:
        segment_words = getattr(segment, "words", None) or []
        if segment_words:
            for w in segment_words:
                text = (w.word or "").strip()
                if not text:
                    continue
                words.append(Word(text=text, start=round(w.start, 3), end=round(w.end, 3)))
        else:
            text = (segment.text or "").strip()
            if text:
                words.append(
                    Word(text=text, start=round(segment.start, 3), end=round(segment.end, 3))
                )
        if on_progress and duration > 0:
            on_progress(min(0.99, float(segment.end) / duration))

    if on_progress:
        on_progress(1.0)
    return _dedupe(words)


# --------------------------------------------------------------------------
# Orchestration
# --------------------------------------------------------------------------
def _rank_subtitle(path: Path) -> tuple[int, int]:
    """Prefer manual over automatic, and json3 over vtt."""
    name = path.name.lower()
    fmt_rank = {".json3": 0, ".srv3": 1, ".vtt": 2, ".srt": 3}.get(path.suffix.lower(), 4)
    # yt-dlp names auto-captions `<name>.<lang>.<ext>` too, so we rely on the
    # caller telling us which set is automatic; this is a tiebreak only.
    auto_rank = 1 if "-orig" in name else 0
    return (fmt_rank, auto_rank)


def transcript_from_subtitles(paths: list[Path]) -> Transcript:
    for path in sorted(paths, key=_rank_subtitle):
        suffix = path.suffix.lower()
        if suffix in {".json3", ".srv3"}:
            words = parse_json3(path)
        elif suffix in {".vtt", ".srt"}:
            words = parse_vtt(path)
        else:
            continue
        if len(words) >= 25:
            log.info("using subtitle track %s (%d words)", path.name, len(words))
            return segment_words(words, source="youtube_subtitles")
    return Transcript()


def build_transcript(
    media_path: Path,
    subtitle_paths: list[Path],
    *,
    duration: float,
    allow_whisper: bool = True,
    on_progress: Callable[[float, str], None] | None = None,
) -> Transcript:
    """Best available transcript, with the source recorded for the UI."""
    if subtitle_paths:
        if on_progress:
            on_progress(0.1, "Reading video captions…")
        transcript = transcript_from_subtitles(subtitle_paths)
        if transcript.available:
            if on_progress:
                on_progress(1.0, "Captions loaded")
            return transcript
        log.info("subtitle files present but unusable, falling back")

    if not (allow_whisper and settings.whisper_enabled):
        return Transcript(source="none")

    if not whisper_available():
        log.info(
            "no subtitles and faster-whisper is not installed - "
            "install backend/requirements-whisper.txt for better clips"
        )
        return Transcript(source="none")

    if on_progress:
        on_progress(0.02, "Transcribing audio…")

    try:
        words = transcribe_with_whisper(
            media_path,
            duration=duration,
            on_progress=(lambda f: on_progress(f, "Transcribing audio…")) if on_progress else None,
        )
    except Exception as exc:  # model download failure, OOM, corrupt audio...
        log.warning("whisper transcription failed: %s", exc)
        return Transcript(source="none")

    if not words:
        return Transcript(source="none")
    return segment_words(words, source="whisper")
