'use strict';

// Shared helpers for the business tools. Node stdlib only - no dependencies, nothing to install.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DATA = path.join(ROOT, 'business', 'data');

function readJSON(name) {
  const file = path.join(DATA, name);
  if (!fs.existsSync(file)) throw new Error(`Missing data file: business/data/${name}`);
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (err) {
    throw new Error(`Invalid JSON in business/data/${name}: ${err.message}`);
  }
}

function writeDoc(relPath, content) {
  const file = path.join(ROOT, relPath);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content.endsWith('\n') ? content : content + '\n');
  return relPath;
}

const money = (n) => `$${Number(n).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const pct = (n) => `${(Number(n) * 100).toFixed(1)}%`;

// Anything unmeasured prints as a placeholder rather than a plausible-looking zero.
const UNMEASURED = 'not yet measured';
const measured = (v, format = (x) => String(x)) =>
  v === null || v === undefined || v === '' ? UNMEASURED : format(v);

// Renders a markdown table from a header array and rows of equal length.
function table(headers, rows) {
  const head = `| ${headers.join(' | ')} |`;
  const sep = `|${headers.map(() => '---').join('|')}|`;
  const body = rows.map((r) => `| ${r.join(' | ')} |`).join('\n');
  return rows.length ? `${head}\n${sep}\n${body}` : `${head}\n${sep}\n| _(none yet)_ |${' |'.repeat(Math.max(0, headers.length - 2))}`;
}

const today = () => new Date().toISOString().slice(0, 10);

const stamp = () =>
  `_Generated by \`tools/${path.basename(process.argv[1] || 'tool.js')}\` on ${today()}. ` +
  `Edit the JSON in \`business/data/\`, not this file._`;

module.exports = { ROOT, DATA, readJSON, writeDoc, money, pct, measured, UNMEASURED, table, today, stamp };
